server:
  port: 8080
  application:
    name: demo

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/testdb
    username: postgres
    password: root

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false                       #开发时关闭缓存,不然没法看到实时页面!
    prefix: classpath:/public/         #配置页面文件路径
    suffix: .html                      #配置页面默认后缀

  flyway:
    enabled: true
    # 禁止清理数据库表
    clean-disabled: false
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 与 baseline-on-migrate: true 搭配使用
    baseline-version: 0
    locations: classpath:migration

logging:
  level:
    com:
      dc:
        pcasweb:
          mapper: debug